### ISSUE TITLE
500 "input.on is not a function" for application/json content-type

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#115]
The following request ends in a 500 error:
```
GET /profile/card? HTTP/1.1
Host: otherjackson.api.swype.io
Content-Type: application/json
cache-control: no-cache
```
The logs report the following error:
```
app errored TypeError: input.on is not a function
    at new SerializerStream (/home/jackson/wac-ldp/node_modules/rdf-serializer-ntriples/lib/SerializerStream.js:9:11)
    at Serializer.import (/home/jackson/wac-ldp/node_modules/rdf-sink/index.js:8:18)
    at toFormat (/home/jackson/wac-ldp/src/lib/rdf/rdfToResourceData.ts:21:35)
    at Object.<anonymous> (/home/jackson/wac-ldp/src/lib/rdf/rdfToResourceData.ts:36:39)
    at Generator.next (<anonymous>)
    at /home/jackson/wac-ldp/dist/lib/rdf/rdfToResourceData.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jackson/wac-ldp/dist/lib/rdf/rdfToResourceData.js:3:12)
    at Object.rdfToResourceData (/home/jackson/wac-ldp/dist/lib/rdf/rdfToResourceData.js:42:12)
    at Object.<anonymous> (/home/jackson/wac-ldp/src/lib/operationHandlers/readBlobHandler.ts:38:35)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jackson/wac-ldp/dist/lib/operationHandlers/readBlobHandler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) +19ms
```

This could probably be fixed by a catch-all that returns a pretty error for unrecognized content-types

It is successful if `Content-Type` is `text/turtle`

Granted, this request probably would never need to happen, but it shouldn't react this way if it does.

**Comment by michielbdejong** [comment]
Tried to reproduce this but can't, can you give a curl command that produces a 500?

**Comment by jaxoncreed** [comment]
I've updated to the dev branch and this is no longer a problem
