### ISSUE TITLE
Patch yields 500

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#121]
```
curl -X PATCH \
  https://otherjackson.api.swype.io/profile/card \
  -H 'Content-Type: application/sparql-update' \
  -H 'Postman-Token: ffa3e344-9fe3-4694-95be-0ea7dc7ecdcc' \
  -H 'authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2RldmVsb3AuZ2VuZXJhdG9yLmlucnVwdC5jb20iLCJhdWQiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJleHAiOjE1NjQxNjAwMDYsImlhdCI6MTU2NDE1NjQwNiwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSXNJbXRwWkNJNkltdGxlWE4wYjNKbExVTklRVTVIUlMxTlJTSjkuZXlKemRXSWlPaUpvZEhSd2N6b3ZMMjkwYUdWeWFtRmphM052Ymk1aGNHa3VjM2Q1Y0dVdWFXOHZjSEp2Wm1sc1pTOWpZWEprSTIxbElpd2libTl1WTJVaU9pSjZkM2xQUVhSVVJsVnFhSEJFUm1wWlUweFJUMnRKV1ZGT1VuWXdkalJxVDI1UGF5MWFkRWhHWjJJd0lpd2ljMmxrSWpvaU1XVTRNbVE0TXpndE1USXpaQzAwT1RNMExXRXlZVGN0TVRFek9EY3dZbVl4WTJRNUlpd2lZWFJmYUdGemFDSTZJbEo0ZDI0NVRFbEJXblZoUmtWV1ZGaGpZVWRTTm5jaUxDSnpYMmhoYzJnaU9pSnJZek5vYjIxaE1VaHpaWEJYT1RSUmIzWmxOVlJSSWl3aVkyNW1JanA3SW1Gc1p5STZJbEpUTWpVMklpd2laU0k2SWtGUlFVSWlMQ0psZUhRaU9uUnlkV1VzSW10bGVWOXZjSE1pT2xzaWRtVnlhV1o1SWwwc0ltdDBlU0k2SWxKVFFTSXNJbTRpT2lJNVJtdzViVUZ1UWkxR1dXdEJlR3d3TjJOek5tdEpaSEJSWDBoNVVuSnNjMFZMTTFWdmJ6bE5NM0ZJUWpGblNGWkVlRU5JZUd4UFkxZHJObU5oYTBGeFpYUjROMWMzY2kxelYxbGpWSGxUUWpkdlZucHdVM1JEVms0MU1uWk9jVmhUTkRNd1J6ZDJRamN3YlZjeWJtbFZPV3BGWWxkb05IcE1UekpzZVdneVlVOUhZamhOU0d0VWQybGFWVUpwVFVGRFZuUkZYM0ZIV1ZsMmVsRjVUemxXU0VrMlZYUTBaV2hRV1ZBM2VsVnVPRk5wWWpVMlVFNW1TMWQwZWpNMWVVdzBjMnB6TlhOelZHUm1aRUZJWkZoT0xYQlhaMU5DZGtGdU5HMXlZVmhhWlVRMVNteDBaVlJDVTFoMWIyRmFOSGxuZEdOTGRGUm9YMEpDUTNGWVEyMXFSSFJxYUZCTlZGUmZVR05UZGtoSGNVOVBVMWMwUkVWRU5qSlVXVkZsVWxVMlNqTnBSRXh4TVhKRFJVOVljVTh5VTBOcmNqUnFjekpuVG1aalRHZGxSRjlGTkdsck1WTnlla3hLYmtaeU9UQjRVVmgwWVhjaWZTd2lZWFZrSWpvaWFIUjBjSE02THk5a1pYWmxiRzl3TG1kbGJtVnlZWFJ2Y2k1cGJuSjFjSFF1WTI5dElpd2laWGh3SWpveE5UWTBNVFU1TWpVMUxDSnBZWFFpT2pFMU5qUXhOVFUyTlRVc0ltbHpjeUk2SW1oMGRIQnpPaTh2WVhCcExuTjNlWEJsTG1sdkluMC5qLXdIbmtwQ01Gdno3MzBRdVJsdzg1aUNvOXNqVVl3U3lUNVd1ZllFTzNFNWxLTVNVUlBnS2FUNUh1ZkZ0RmxFSUFsVXpCWUlrN1RMbFM2V2xLNnpxbEFFa25DdGJlU2xFR3JUczJha3pRS214WHlPVnp0dFBkMF9ka2pGekd4WEtsUmJ5bXlZdFB0LVZBQnBHdTN6Q3M3WGZqNzNWOVlBanJqN0U2bE8yNGhzTThjVmVkNDROdjJMMGNHUUI0U2M4V2NkQzRmNGNZeVItLWtpRFVqTjNpR2NQRVJVeFllTnF5U0FxelpqOE1aZlVuOWVYWm54WmQ3QWlGSXhzTkREbnVfWW9jT0hRV2FSOURndW5URWFyZGVwMWhGSWV1U00yM3F6bFJMS2NBUWg5c1pfbEN0Q0NkWUVZNTB1QmJPNEJ5MVVlOGJ5VlM1RGFRSnplQmpEQUEiLCJ0b2tlbl90eXBlIjoicG9wIn0.tJiuhOQft2y47XlUL2eD0Mh4c82HT2fBNiOHeliwrlrb9zcLgV6ZGBqLnmgd7a3_E9TbaJXAHTIvVHnEmo8Xqy7w0Xcvi_r7iou05-CCLifcsFgFg9YvRYShmoiEsLBwYXX-Z-ICLhf3AxScMTp-FmYyL-_UBmQ_Bys5u10PPryaDU6x4T-h7ulWC1pmqOA-IKmiM8BGKkvLQ6z0IXoisie01pU-yBDysrXxEUF22Z2X6rNPeobyDS3cA3QYBstzRTidYfVkonk7-oznPtqjFXGtHcufj1_k783HlutSO6PRLRELZJoeoKEkySTl1NxmcGqY5A9IHYmYPFC3RA6lZA' \
  -H 'cache-control: no-cache' \
  -d 'INSERT DATA {
  <https://otherjackson.api.swype.io/profile/card#me> <http://www.w3.org/2006/vcard/ns#fn> "Jackson".
}'
```

Yields a 500 error with this printed in the logs:

```
 app errored TypeError: iri.includes is not a function
    at new NamedNode (/home/jackson/wac-ldp/node_modules/rdflib/lib/named-node.js:56:14)
    at IndexedFormula.sym (/home/jackson/wac-ldp/node_modules/rdflib/lib/formula.js:690:14)
    at Promise (/home/jackson/wac-ldp/src/lib/rdf/StoreManager.ts:192:95)
    at new Promise (<anonymous>)
    at StoreManager.<anonymous> (/home/jackson/wac-ldp/src/lib/rdf/StoreManager.ts:191:11)
    at Generator.next (<anonymous>)
    at /home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:3:12)
    at StoreManager.applyPatch (/home/jackson/wac-ldp/dist/lib/rdf/StoreManager.js:169:16)
    at Object.<anonymous> (/home/jackson/wac-ldp/src/lib/operationHandlers/updateBlobHandler.ts:24:50)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jackson/wac-ldp/dist/lib/operationHandlers/updateBlobHandler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) +11ms
```

**Comment by michielbdejong** [comment]
Reproduced.
First window:
```sh
DEBUG=* SKIP_WAC=1 npm start
[...]
%capp %cerrored%c +13ms color: #CC6633 color: inherit color: #CC6633 TypeError: iri.includes is not a function
```
second window:
```sh
curl -X PUT -d '' -H'If-None-Match: *' -H'Content-Type: text/turtle' http://localhost:8080/profile/card
Created
curl -X PATCH   http://localhost:8080/profile/card   -H 'Content-Type: application/sparql-update'   -d 'INSERT DATA { <https://otherjackson.api.swype.io/profile/card#me> <http://www.w3.org/2006/vcard/ns#fn> "Jackson". }'
Internal server error
```

**Comment by michielbdejong** [comment]
uncommented a failing test for this. Apparently it did work when I wrote https://github.com/inrupt/wac-ldp/blob/065ab752f2f40364da2e41869a403ff9bb03f9f2/src/lib/operations/updateBlob.ts, will see what changed.

**Comment by michielbdejong** [comment]
Fixed in dev
