### ISSUE TITLE
412 Precondition Failed on PUT

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#137]
Request:

```
curl -X PUT \
  https://otherjackson.api.swype.io/coolNotes/index.ttl \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Accept-Language: en-US,en;q=0.5' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 432' \
  -H 'Host: otherjackson.api.swype.io' \
  -H 'Origin: https://otherjackson.api.swype.io' \
  -H 'Postman-Token: e49d853d-5948-4562-a9eb-88cbdd54491f,41a14291-3d8d-43b2-88eb-a404e92b87b0' \
  -H 'Referer: https://otherjackson.api.swype.io/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0' \
  -H 'authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJhdWQiOiJodHRwczovL290aGVyamFja3Nvbi5hcGkuc3d5cGUuaW8iLCJleHAiOjE1NjQ1MjU5NDEsImlhdCI6MTU2NDUyMjM0MSwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSXNJbXRwWkNJNkltdGxlWE4wYjNKbExVTklRVTVIUlMxTlJTSjkuZXlKemRXSWlPaUpvZEhSd2N6b3ZMMjkwYUdWeWFtRmphM052Ymk1aGNHa3VjM2Q1Y0dVdWFXOHZjSEp2Wm1sc1pTOWpZWEprSTIxbElpd2libTl1WTJVaU9pSnhVVEY1WlRsbE0yMHdSMms1UTFGT1IzcFVOek5VYlZSeE9VdHVZVVJMZDFGTVRtdFJTazF2WkVaM0lpd2ljMmxrSWpvaVptUTJaVGN3Tm1RdE5qTXlNQzAwTVRNMExXRTJaREF0WmpJM09EVTJOMkUzTUdRM0lpd2lZWFJmYUdGemFDSTZJazQ0YURSSGRWRnJhMVZ5ZVhOZlZsUjNlRzU0ZVhjaUxDSnpYMmhoYzJnaU9pSm5VWGN5WDBseVIwOXRhM2RVTm14SExWSlViWFZuSWl3aVkyNW1JanA3SW1Gc1p5STZJbEpUTWpVMklpd2laU0k2SWtGUlFVSWlMQ0psZUhRaU9uUnlkV1VzSW10bGVWOXZjSE1pT2xzaWRtVnlhV1o1SWwwc0ltdDBlU0k2SWxKVFFTSXNJbTRpT2lKM1pEWndPVkp1YUhkc2VHaDRXSHBSUWtOVFRqUjFZbHBNVm5ReVJHTkRZbXB6VVdKbVJGWXhUMkV0Y25GdU1XbE5XRFp0YUhndFRVdHFTVlpCVURaNWRWbDRNMlowWlhjNE9FNWZVV2x1YjJrMk1GRk9TVTgzU1RSbmIyOUdWMEp6T1RsVGFrRmlZM0JMZGkxeWVETkxRVWR4UTBwTVgyaGlkbTlCWVhwcFNWOW5aWFozWVZsd1dtRlNMWE0yYkZob1QyNU9RM0pUTW5KSFdEWmtNRzgzV1ZaRFlUUnRNSFJaTVU0eWVXWlZXa3N5VDJoWVJFSnBOMWxFWWtORmNESmZNRU0xUTNaaWNEbHZaSFJsUVZCNmJFaElZbk5PYnpWaU5GZHFMVGQ0TFdsYVJHUTBZa05NTkhoTWFFOWlPRzVYWlZFNFp5MU9jR2RzVFUxSmJqWkdSVGRwVW1WUmExY3pXVE41YkRsbFF6aHhZV2RNY21oS1pXbHNaVVV5UVhCUk5qTXRaRU5ZV0ZCWFptZFlZeTFFVDJwVlZXVlZZM1ZLZDBGeFRuWnphMVZIY0RkR2MyOUZOVkZNVlRSVmVsUXpaM3B4T1hjaWZTd2lZWFZrSWpvaWFIUjBjSE02THk5dmRHaGxjbXBoWTJ0emIyNHVZWEJwTG5OM2VYQmxMbWx2SWl3aVpYaHdJam94TlRZME5USTBNakF4TENKcFlYUWlPakUxTmpRMU1qQTJNREVzSW1semN5STZJbWgwZEhCek9pOHZZWEJwTG5OM2VYQmxMbWx2SW4wLmgwMEg0dU5WUUp2OFpVZXY0ZnI1cE92QW9pZUpWeGx6c3ZMQjVvN21ObndRZU1JeHNMc1lpa1dZd1pCRmZpYmduWHJ5Mm9jemwwNzcyS21rMlVUSmtURlJGVlRIUFVRVVpkT1FCSWx3cy1pNUZhaFVzVVo4ZDlTeG1lV0g1S3B2RkY1MDNEYy1ZNWxmUW1hVThZSS1wRFVDVDV4S2J3UjRJY2l4b3M1ZWtGel95QVBHeTllb1VaUmlOZWlrS01weFFDMTU3bFNGeXBkSHhUR1VadVhqak5SVTRvS0NWRDNoejkyTER5ZmtydHQtRTRpTVVyRUNnaWQyRm43WkViZHJ0LUlyWk4wMG5VSTNXVTlGRUFOUTN3M19ES1VoNlJIaTBnOG4tZlpwVWtoZGp3THBjbTRma1JyaDFwa3hrX3liWF8xZ0txcHV0dXhreDlCVXZkbDF5ZyIsInRva2VuX3R5cGUiOiJwb3AifQ.NFfyLRUvnI5uQOpRD9Ro0RD_b0-lLlaZCuFcvAGBFoGedYoCYPJzSkpAMMVMt8NHgI6N-Hm1yVML5eLKZCG5rik765O6esuMNHx9_AhDjUjOjM1grqgWvHTo4u2Wzq8Ly7VucP8-urNjHFMr8vd1GjyPkzdW_E8XWJZxNIYmZsGEoiT7qmRevT1RszlWXe1siJsRrRXKvQPgoq9aOyARkJo7ndguDATmyZ91ABwNajmFYZdWxzsURgDY8IgKKhWEiSV3slPxFyR8aYf9BquvOAv5zAjegAPewy_gs2inCW2c7kfEQkE0E4ESs1hHznugiI9W7BCZ1uBNigfEpaMpAQ' \
  -H 'cache-control: no-cache' \
  -H 'content-type: text/turtle' \
  -d '@prefix : <#>.
@prefix p: <http://www.w3.org/ns/pim/pad#>.
@prefix n0: <http://purl.org/dc/elements/1.1/>.
@prefix c: </profile/card#>.
@prefix XML: <http://www.w3.org/2001/XMLSchema#>.
@prefix n: <http://rdfs.org/sioc/ns#>.

:this
    a p:Notepad;
    n0:author c:me;
    n0:created "2019-07-30T21:32:21Z"^^XML:dateTime;
    n0:title "Shared Notes";
    p:next :this_line0.
:this_line0 n0:author c:me; n:content ""; p:next :this.

'
```

This time, a 412 does not apply at all (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412).

Here is the error in the logs:
```
 write-blob-handler operation writeBlob! false +10m
  write-blob-handler checking If-Match presence false undefined false true false +0ms
  write-blob-handler attempt to overwrite existing resource +0ms
  app errored { Error: error result
    at Object.<anonymous> (/home/jackson/wac-ldp/src/lib/operationHandlers/writeBlobHandler.ts:26:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jackson/wac-ldp/dist/lib/operationHandlers/writeBlobHandler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) resultType: 2 } +6ms
  app error has a responseStatus 2 +1ms
  app response is { Error: error result
    at Object.<anonymous> (/home/jackson/wac-ldp/src/lib/operationHandlers/writeBlobHandler.ts:26:13)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jackson/wac-ldp/dist/lib/operationHandlers/writeBlobHandler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) resultType: 2 } +0ms

```

**Comment by michielbdejong** [comment]
OK, so what happened here was a new behaviour I introduced, which is that PUT requires either an `If-None-Match` or `If-Match` header, let me find the spec reference. The 412 might be incorrect, although it does count as a 'precondition', i think

**Comment by michielbdejong** [comment]
Ah right, it should be 'status code 428 (Precondition Required)', see section 4.2.4.5 of https://www.w3.org/TR/ldp/#ldpr-resource.

**Comment by michielbdejong** [comment]
Fixed in dev, will add a regression test for it
