### ISSUE TITLE
create data container on the fly

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#167]
```sh
%cBlobTree %cdetermined containerhood%c +30ms color: #9933FF color: inherit color: #9933FF / true 
%cread-container-handler %coperation readContainer!%c +30ms color: #00CC33 color: inherit color: #00CC33
%cread-container-handler %c'color: #00CC33'%c +0ms color: inherit ContainerNssCompat {
  path: Path { segments: [ 'v1', 'localhost:8080' ], isContainer: true },
  tree: BlobTreeNssCompat {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    dataDir: './data'
  },
  filePath: 'data/localhost'
} color: #00CC33
%capp %cerrored%c +2ms color: #CC6633 color: inherit color: #CC6633 [Error: ENOENT: no such file or directory, scandir 'data/localhost'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'data/localhost'
}
%capp %cerror has no resultType%c +0ms color: #CC6633 color: inherit color: #CC6633 ENOENT: no such file or directory, scandir 'data/localhost' [Error: ENOENT: no such file or directory, scandir 'data/localhost'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'data/localhost'
}
%capp %cresponse is%c +0ms color: #CC6633 color: inherit color: #CC6633 ErrorResult: error result
    at WacLdp.<anonymous> (/ldp-testsuite/dist/lib/core/WacLdp.js:131:32)
    at Generator.throw (<anonymous>)
    at rejected (/ldp-testsuite/dist/lib/core/WacLdp.js:6:65) {
  resultType: 11
}
%cHttpResponder %csendHttpResponse!%c +28ms color: #33CCCC color: inherit color: #33CCCC ErrorResult: error result
    at WacLdp.<anonymous> (/ldp-testsuite/dist/lib/core/WacLdp.js:131:32)
    at Generator.throw (<anonymous>)
    at rejected (/ldp-testsuite/dist/lib/core/WacLdp.js:6:65) {
  resultType: 11
}

**Comment by michielbdejong** [comment]
this was fixed
