### ISSUE TITLE
input.on is not a function

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#80]
(bug i'm seeing in the version-0.3 branch now)
```sh
%capp %cerrored%c +13ms color: #CC6633 color: inherit color: #CC6633 TypeError: input.on is not a function
    at new SerializerStream (/Users/michiel/gh/inrupt/wac-ldp/node_modules/rdf-serializer-jsonld/lib/SerializerStream.js:13:11)
    at new SerializerStreamExt (/Users/michiel/gh/inrupt/wac-ldp/node_modules/rdf-serializer-jsonld-ext/lib/SerializerStream.js:15:19)
    at Serializer.import (/Users/michiel/gh/inrupt/wac-ldp/node_modules/rdf-sink/index.js:8:18)
    at toFormat (/Users/michiel/gh/inrupt/wac-ldp/dist/lib/rdf/rdfToResourceData.js:21:37)
    at Object.<anonymous> (/Users/michiel/gh/inrupt/wac-ldp/dist/lib/rdf/rdfToResourceData.js:36:27)
```

**Comment by michielbdejong** [comment]
looks like this was fixed
