### ISSUE TITLE
input.on is not a function when calling fetchGraph

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/wac-ldp#94]
I get the following error when calling `fetchGraph(PROFILE_URL)`

```
TypeError: input.on is not a function
   at new ParserStream (/home/jackson/archiveIDPConfiguration/node_modules/wac-ldp/node_modules/rdf-parser-n3/lib/ParserStream.js:34:11)
   at Parser.import (/home/jackson/archiveIDPConfiguration/node_modules/wac-ldp/node_modules/rdf-sink/index.js:8:18)
   at readRdf (/home/jackson/archiveIDPConfiguration/node_modules/wac-ldp/dist/lib/rdf/RdfLayer.js:56:25)
   at CachingRdfLayer.<anonymous> (/home/jackson/archiveIDPConfiguration/node_modules/wac-ldp/dist/lib/rdf/RdfLayer.js:109:36)
   at Generator.next (<anonymous>)
   at fulfilled (/home/jackson/archiveIDPConfiguration/node_modules/wac-ldp/dist/lib/rdf/RdfLayer.js:4:58)
   at process._tickCallback (internal/process/next_tick.js:68:7)
```

Full example:

Call `rdfLayer.fetchGraph('https://otherjackson.api.swype.io/profile/card')`

It looks like it goes here https://github.com/inrupt/wac-ldp/blob/master/src/lib/rdf/RdfLayer.ts#L93 instead of calling locally (This is documented in https://github.com/inrupt/wac-ldp/issues/93)

It goes to fetch the profile's .acl. At this point https://github.com/inrupt/wac-ldp/blob/master/src/lib/rdf/RdfLayer.ts#L54 resource data is:
```
{ contentType: 'text/turtle',
  body:
   '@prefix acl: <http://www.w3.org/ns/auth/acl#>.\n@prefix  foaf:  <http://xmlns.com/foaf/0.1/>.\n<#owner>\n  a acl:Authorization;\n  acl:agent <https://otherjackson.api.swype.io/profile/card#me>;\n  acl:accessTo </>;\n  acl:default </>;\n  acl:mode\n    acl:Read, acl:Write, acl:Control.\n<#public>\n  a acl:Authorization;\n  acl:agent foaf:Agent;\n  acl:accessTo </>;\n  acl:mode\n    acl:Read.',
  etag: 'iEJxBc10MRssgODZrsSk/g==',
  rdfType: 1 }
```

And it does successfully make a body stream but errors once inserting it into https://github.com/inrupt/wac-ldp/blob/master/src/lib/rdf/RdfLayer.ts#L42

**Comment by michielbdejong** [comment]
thanks! yes, the whole QuadStreams thing there is a bit of a mess, that same error is causing https://github.com/inrupt/wac-ldp/issues/59 iirc. will have a look at it tonight.

**Comment by michielbdejong** [comment]
Ah yes, https://github.com/inrupt/wac-ldp/blob/master/src/lib/rdf/RdfLayer.ts#L88 needs to be adapted to the multi-user configuration

**Comment by michielbdejong** [comment]
please try again now that #93 is fixed?

**Comment by michielbdejong** [comment]
it seems this was fixed
